apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-delete-all-completed-pods
  namespace: demo

---

# 2. Create a role

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo
  name: delete-all-completed-pods-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]

---

# 3. Attach the role to the service account

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-all-completed-pods-rolebinding
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: delete-all-completed-pods-role
subjects:
- kind: ServiceAccount
  name: sa-delete-all-completed-pods
  namespace: demo

---

# 4. Create a cronjob (with a crontab schedule) using the service account to check for completed jobs

apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-all-completed-pods
  namespace: demo
spec:
  schedule: "0 16 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-delete-all-completed-pods
          containers:
          - name: kubectl-container
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            # I'm using bitnami kubectl, because the suggested kubectl image didn't had the `field-selector` option
            command: ["sh", "-c", "kubectl delete pods --field-selector=status.phase==Succeeded -n demo"]
          restartPolicy: Never
          
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-all-error-pods
  namespace: demo
spec:
  schedule: "0 16 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-delete-all-completed-pods
          containers:
          - name: kubectl-container
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            # I'm using bitnami kubectl, because the suggested kubectl image didn't had the `field-selector` option
            command: ["sh", "-c", "kubectl delete pod --field-selector=status.phase==Failed -n demo"]
          restartPolicy: Never

